spring:
  application:
    name: api-gateway
env: dev
zuul:
  routes:
    order: /order/**
    product: /productServer6/**
#   ignored-patterns:
#     - /**/product/listForOrder
    productServer:
      path: /productServer/**
      serviceId: product
      sensitiveHeaders: 
