spring:
  application:
    name: api-gateway
env: dev
zuul:
  #全部服务忽略敏感头，可传递cookie
  sensitive-headers:
  routes:
    user: 
      path: /user/**
      serviceId: user
      sensitiveHeaders: 
    order: /order/**
    product: /productServer6/**
#   ignored-patterns:
#     - /**/product/listForOrder
    productServer:
      path: /productServer/**
      serviceId: product
      sensitiveHeaders: 
