spring:
  application:
    name: api-gateway
env: dev
zuul:
  routes:
    product: /productServer/**
#   ignored-patterns:
#     - /**/product/listForOrder
#     productServer:
#       path: /productServer/**
#       serviceId: product
